from enum import StrEnum


class ComputationFailure(StrEnum):
    WINDOW_TOO_SHORT = "WINDOW_TOO_SHORT"
    NO_SPECTRAL_PEAK = "NO_SPECTRAL_PEAK"
    INSUFFICIENT_BEATS = "INSUFFICIENT_BEATS"
    EXCESSIVE_ARTIFACTS = "EXCESSIVE_ARTIFACTS"
    LOW_SIGNAL_TO_NOISE = "LOW_SIGNAL_TO_NOISE"
    HEART_RATE_UNAVAILABLE = "HEART_RATE_UNAVAILABLE"
    NO_RESPIRATORY_COMPONENT = "NO_RESPIRATORY_COMPONENT"
    RESPIRATORY_COMPONENTS_DISAGREE = "RESPIRATORY_COMPONENTS_DISAGREE"
