from enum import StrEnum


class IssueCode(StrEnum):
    COMPUTATION_FAILED = "COMPUTATION_FAILED"
    WINDOW_TOO_SHORT = "WINDOW_TOO_SHORT"
    MISSING_DATA_HIGH = "MISSING_DATA_HIGH"
    MISSING_DATA_EXCESSIVE = "MISSING_DATA_EXCESSIVE"
    SIGNAL_QUALITY_LOW = "SIGNAL_QUALITY_LOW"
    SIGNAL_QUALITY_UNUSABLE = "SIGNAL_QUALITY_UNUSABLE"
    OUT_OF_PHYSIOLOGICAL_RANGE = "OUT_OF_PHYSIOLOGICAL_RANGE"
    SUDDEN_JUMP = "SUDDEN_JUMP"
    TEMPORAL_UNSTABLE = "TEMPORAL_UNSTABLE"
    CROSS_ROI_INCONSISTENT = "CROSS_ROI_INCONSISTENT"
    LOW_CONFIDENCE = "LOW_CONFIDENCE"
    VERY_LOW_CONFIDENCE = "VERY_LOW_CONFIDENCE"
    MISSING_FEATURES = "MISSING_FEATURES"
    PULSE_PRESSURE_INVALID = "PULSE_PRESSURE_INVALID"
